// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwdvwrOeONO0l9Hx4e7qeEiUQWTvGXONs',
    appId: '1:936698874007:web:0950366e0b3c6865ce41d2',
    messagingSenderId: '936698874007',
    projectId: 'houta-flutter',
    authDomain: 'houta-flutter.firebaseapp.com',
    storageBucket: 'houta-flutter.appspot.com',
    measurementId: 'G-E7YYCHG4C6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-6LMjELOG7LZuiM3mnZp9OibQr6vHTK8',
    appId: '1:936698874007:android:557847927f1510a6ce41d2',
    messagingSenderId: '936698874007',
    projectId: 'houta-flutter',
    storageBucket: 'houta-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBKY6T3-p8C7ju2oIP5wdTjzYGxFZ1OBI',
    appId: '1:936698874007:ios:92906ff6971032cfce41d2',
    messagingSenderId: '936698874007',
    projectId: 'houta-flutter',
    storageBucket: 'houta-flutter.appspot.com',
    iosClientId: '936698874007-k95brg6pkr50da5jv9hlms7jtc9nhfeo.apps.googleusercontent.com',
    iosBundleId: 'com.example.houta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBKY6T3-p8C7ju2oIP5wdTjzYGxFZ1OBI',
    appId: '1:936698874007:ios:c9b571af925e5246ce41d2',
    messagingSenderId: '936698874007',
    projectId: 'houta-flutter',
    storageBucket: 'houta-flutter.appspot.com',
    iosClientId: '936698874007-je2j2f822hsagqvsetq1s6anrc2bmp2l.apps.googleusercontent.com',
    iosBundleId: 'com.example.houta.RunnerTests',
  );
}
